services:
  server:
    build: ./server
    image: chess-server
    container_name: chess-server
    ports:
      - 5000:5000
    networks:
      - chess_network
  
  client:
    build: ./client
    image: chess-client
    container_name: chess-client
    ports:
      - 3000:80
    depends_on:
      - server
    networks:
      - chess_network

networks:
  chess_network:
    name: chess_network
    driver: bridge